name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        env:
          PING_URL: ${{ secrets.RENDER_HEALTH_URL }}
        run: |
          if [ -z "$PING_URL" ]; then
            echo "RENDER_HEALTH_URL secret is not set. Set it to your Render health URL (e.g., https://your-app.onrender.com/api/health). Skipping."
            exit 0
          fi
          curl -sS --max-time 10 "$PING_URL" || true 